apiVersion: v1
kind: Service
metadata:
  name: csvanalytics-service
spec:
  selector:
    app: csvanalytics
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081 # Optional: can be omitted for auto-assign
